name: Prasad

on: push

jobs: 
  super-lint:
    name: Lint code base
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Super-Liner
        uses: github/mygitactions
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
